import { beachfront } from "../../assets/images/Roomora/Beachfront Penthouse";
import { luxuryApartment } from "../../assets/images/Roomora/Luxury Apartment";
import { mallsideLuxury } from "../../assets/images/Roomora/Mallside Luxury";
import { mountainView } from "../../assets/images/Roomora/Mountain View Luxury";
import { sodnacSerenity } from "../../assets/images/Roomora/Sodnac Serenity";
import { scenicPlots } from "../../assets/images/Roomora/Scenic Plots Available";
import { gardenVilla } from "../../assets/images/Roomora/Garden Villa Retreat";
import { touristHeaven } from "../../assets/images/Roomora/Tourist Haven Opportunity";
import { mokaEstate } from "../../assets/images/Roomora/Moka Estate Elegance";
import { modernMoka } from "../../assets/images/Roomora/Modern Moka Retreat";
import { commercialPotential } from "../../assets/images/Roomora/Commercial Potential";
import { centralImage } from "../../assets/images/Roomora/Central Luxury Living";
import { seasideVilla } from "../../assets/images/Roomora/Seaside Villa Dream";
import { ebeneCity } from "../../assets/images/Roomora/Ebene City Gem";
import { palmyre } from "../../assets/images/Roomora/Palmyre Prestige";


export const estates = [
  {
    id: `REALES001`,
    title: `Beachfront Penthouse`,
    description: [
      `Discover unparalleled luxury with this stunning 269m² beachfront penthouse in Palmar, located on the 2nd floor next to Seasense Hotel. Boasting 3 bedrooms, including an ensuite, plus an additional bathroom, and a laundry room. The fully equipped open-plan kitchen with a dishwasher, and a spacious living and dining area, lead to a large verandah offering breathtaking sea views. Amenities include a swimming pool, 2 private parking spaces, and 24/7 security, all for Rs45M negotiable, exclusive of fees. Your dream home awaits by the sea.`,
    ],
    address:"Delhi",
    price: "Rs 10k/day",
    averageprice: "  269m²",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    // thumbnail: beachfront.img1,
    images: [beachfront.img1, beachfront.img2, beachfront.img3, beachfront.img4,beachfront.img5,beachfront.img6,beachfront.img7, beachfront.img8]
  },
  {
    id: `REALES002`,
    title: `Luxury Apartment`,
    description: [
      `Dive into luxury with our elegantly furnished, brand-new apartment in the vibrant heart of Flic en Flac, available from June 1st. Perfectly situated near all essential amenities, this stunning residence offers unparalleled comfort and style. With two master ensuite bedrooms and an additional guest toilet, it caters to your privacy and convenience. The heart of this home is its open-plan kitchen, which seamlessly transitions into a spacious living and dining area, opening onto a serene balcony for your leisure moments. Exclusive access to premium facilities such as a lift, swimming pool, gym, and reception desk enhances your living experience. Embrace a lifestyle of sophistication and ease for just Rs35k/month. This is your invitation to luxury living in one of the most sought-after locations.`,
    ],
    address:"Mumbai",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    images: [luxuryApartment.img1, luxuryApartment.img2, luxuryApartment.img3, luxuryApartment.img4,luxuryApartment.img5,luxuryApartment.img6,luxuryApartment.img7, luxuryApartment.img8]
  },
  {
    id: `REALES003`,
    title: `Mallside Luxury`,
    description: [
      `Embrace the epitome of convenience and luxury with this stunning, fully furnished apartment in Grand Bay la Croisette, open to foreigners. Spanning two levels, this home features high-quality furnishings, a Schmidt kitchen, a spacious air-conditioned living and dining area, and an open-plan kitchen. Two air-conditioned en-suite bedrooms ensure privacy and comfort. Exclusive amenities include a lift, swimming pool, parking, and security, all for Rs13.5M, exclusive of fees. Live where luxury meets lifestyle in one of Mauritius's prime locations.`,
    ],
    address:"Noida",
    price: "Rs 10k/day",
    
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    images: [mallsideLuxury.img1, mallsideLuxury.img2, mallsideLuxury.img3, mallsideLuxury.img4,mallsideLuxury.img5,mallsideLuxury.img6,mallsideLuxury.img7, mallsideLuxury.img8]
  },
  {
    id: `REALES004`,
    title: `Mountain View Luxury`,
    description: [
      `Seize a lifetime opportunity with no agency fees and a 5% government rebate under the Home Ownership Scheme! Our luxurious apartments, accessible to foreigners, offer breathtaking views of the Moka Mountain Range. Located near Minissy Waterfall and nestled along a river, enjoy easy access to Ebene Cybercity, Moka Smart City, and Tribeca Mall. Features include a 10m x 25m pool, clubhouse, fitness centre, kids' playground, private lounge with WiFi, barbecue area, and more. With 60% completion, ready by June 2024, only a few units remain: 1BR at Rs6M, 2BR at Rs8.3M, 3BR at Rs11M. Don't miss out!`,
    ],
    address:"Kashmir",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    images: [mountainView.img1, mountainView.img2, mountainView.img3, mountainView.img4,mountainView.img5,mountainView.img6,mountainView.img7]
  },
  {
    id: `REALES005`,
    title: `Sodnac Serenity`,
    description: [
      `Seize a lifetime opportunity with no agency fees and a 5% government rebate under the Home Ownership Scheme! Our luxurious apartments, accessible to foreigners, offer breathtaking views of the Moka Mountain Range. Located near Minissy Waterfall and nestled along a river, enjoy easy access to Ebene Cybercity, Moka Smart City, and Tribeca Mall. Features include a 10m x 25m pool, clubhouse, fitness centre, kids' playground, private lounge with WiFi, barbecue area, and more. With 60% completion, ready by June 2024, only a few units remain: 1BR at Rs6M, 2BR at Rs8.3M, 3BR at Rs11M. Don't miss out!`,
    ],
    address:"Varanasi",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    images: [sodnacSerenity.img1, sodnacSerenity.img2, sodnacSerenity.img3, sodnacSerenity.img4,sodnacSerenity.img5,sodnacSerenity.img6,sodnacSerenity.img7,sodnacSerenity.img8]
  },
  {
    id: `REALES006`,
    title: `Scenic Plots Available`,
    description: [
      `Limited plots now available in the prestigious gated estate of Jardin D'Anna, Flic en Flac Phase 2. These exclusive parcels face the jogging track and boast superb sea views, offering a serene and picturesque setting for your dream home. For more information and to arrange a viewing, please contact Mahikaz Properties at 57112980. Don't miss this rare opportunity to own a piece of paradise.`,
    ],
    address:"Banglore",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    images: [scenicPlots.img1, scenicPlots.img2, scenicPlots.img3]
  },
  {
    id: `REALES007`,
    title: `Beachside Villa Bliss`,
    description: [
      `Nestled in the prestigious gated estate of Jardin D'Anna in Flic en Flac, this exquisite villa offers a serene garden oasis. Available for rent at Rs85k/month, inclusive of pool and garden maintenance, it features three bedrooms (one ensuite), two common bathrooms, an open-plan and a grease kitchen, plus a laundry area. The living and dining area opens onto the pool deck, overlooking a salt-chlorinated pool and a lush garden filled with herbs and plants. Embrace tranquil living in a sought-after location.`,
    ],
    address:"Goa",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    images: [gardenVilla.img1, gardenVilla.img2, gardenVilla.img3, gardenVilla.img4,gardenVilla.img5,gardenVilla.img6,gardenVilla.img7,gardenVilla.img8]
  },
  {
    id: `REALES008`,
    title: `Tourist Haven Opportunity`,
    description: [
      `Seize this rare opportunity to own Lagon Bleu, an established tourist accommodation business in Flic en Flac, just steps away from the beach and behind Manisa hotel. This lucrative venture comprises three villas totaling 9 bedrooms, along with staff quarters and a swimming pool, all licensed by the tourism authority. Offered at Rs7.5M per 3-bedroom villa or acquire the entire property for Rs21M. A golden chance to invest in a thriving location.`,
    ],
    address:"Meghalaya",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    images: [touristHeaven.img1, touristHeaven.img2]
  },
  {
    id: `REALES009`,
    title: `Moka Estate Elegance`,
    description: [
      `Discover the perfect canvas for your dream home with a beautiful 257-toise plot in the prestigious gated estate of Courchamps, Moka. Offered at Rs11M, exclusive of Notary, Registration, and Agency fees, this is a rare opportunity to secure premium land in a sought-after location. For more details or to arrange a viewing, contact Mahikaz Properties at 57112980. Secure your piece of paradise in Moka today.`,
    ],
    address:"Chandigarh",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    // thumbnail: beachfront.img1,
    images: [mokaEstate.img1, mokaEstate.img2]
  },
  {
    id: `REALES0010`,
    title: `Modern Retreat`,
    description: [
      `Experience luxury living in Moka with this newly built villa in Courchamps, ready from March 1, 2024. This exquisite property features four air-conditioned bedrooms (two ensuite), a common bathroom, and a Mobalpa fitted kitchen. The spacious living/dining area opens onto a large verandah with views of the swimming pool. Also includes a laundry, garage, and 24/7 security. Rent of Rs85k/month covers pool and garden maintenance, offering a hassle-free lifestyle in one of Moka's premier gated communities.`,
    ],
    address:"Jaipur",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    // thumbnail: beachfront.img1,
    images: [modernMoka.img1, modernMoka.img2, modernMoka.img3, modernMoka.img4,modernMoka.img5,modernMoka.img6,modernMoka.img7, modernMoka.img8]
  },
  {
    id: `REALES0011`,
    title: `Commercial Potential`,
    description: [
      `Unlock a prime investment in Vieux Quatre Bornes with an atypical 270m² house on a 220-toise plot, near all amenities. Perfect for conversion into offices or other commercial ventures, this property is priced at Rs15M. A strategic location combined with versatile use options makes this an unmissable opportunity for investors seeking to capitalize on the area's commercial potential.`,
    ],
    address:"Rishikesh",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    // thumbnail: beachfront.img1,
    images: [commercialPotential.img1, commercialPotential.img2, commercialPotential.img3, commercialPotential.img4,commercialPotential.img5,commercialPotential.img6,commercialPotential.img7, commercialPotential.img8]
  },
  {
    id: `REALES0012`,
    title: `Central Luxury Living`,
    description: [
      `Presenting a prestigious new project of luxurious apartments, accessible to foreigners and perfectly located minutes from Bagatelle Mall, amidst a lush riverside and waterfall setting. Spanning 318m², each apartment features four bedrooms (one ensuite), three additional bathrooms, a large living room, dining room, fully equipped kitchen, laundry room, and two covered car parks. Residents enjoy exclusive access to a club house, swimming pool, and gym. With only a few units remaining at Rs32M each, seize this opportunity for unparalleled luxury and convenience.`,
    ],
    address:"Agra",
    price: " Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    // thumbnail: beachfront.img1,
    images: [centralImage.img1, centralImage.img2, centralImage.img3, centralImage.img4,centralImage.img5,centralImage.img6,centralImage.img7, centralImage.img8]
  },
  {
    id: `REALES0013`,
    title: `Seaside Villa Dream`,
    description: [
      `Embrace the opportunity to own a newly built villa in the prestigious Jardin D'Anna Phase 2, Flic en Flac. This luxurious 245m² villa is situated on a 495m² plot, offering 4 bedrooms (one ensuite), 2 additional bathrooms, and an open plan kitchen equipped with cabinets and appliances. The living and dining area opens to a swimming pool, with bedrooms leading to a balcony showcasing sea views. Features include air conditioning, a pergola, a 5.5m x 3.5m slate pool, electric gate, CCTV, internet, water tanks, landscaping, solar water heater, and double carport. Construction is underway for delivery in June 2024 at Rs22M.`,
    ],
    address:"Near Bagatelle Mall",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    // thumbnail: beachfront.img1,
    images: [seasideVilla.img1,seasideVilla.img2,seasideVilla.img3,seasideVilla.img4,seasideVilla.img5,seasideVilla.img6,seasideVilla.img7,seasideVilla.img8]
  },
  {
    id: `REALES0014`,
    title: `Ebene City Gem`,
    description: [
      `Seize this rare opportunity to own a prime 196-toise plot in the heart of Ebene City, a location renowned for its convenience and proximity to amenities and the motorway. Priced at Rs11.5M, exclusive of Registration, Notary, and Agency fees, this beautiful plot offers the perfect foundation for your dream project in a coveted urban setting. Don't miss out on this exceptional offering in one of the most sought-after areas.`,
    ],
    address:"Gurgaon",
    price: "Rs 10k/day",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    // thumbnail: beachfront.img1,
    images: [ebeneCity.img1,ebeneCity.img2]
  },
  {
    id: `REALES0015`,
    title: `Palmyre Prestige`,
    description: [
      `: Golden opportunity awaits with this stunning corner plot of 2113m² (556 toises) in the gated estate of Domaine de Palmyre, Rivière Noire. Offering unparalleled potential for your dream home in a prestigious community, this plot is available for Rs12M. Experience the epitome of luxury and privacy in a serene setting. Contact Mahikaz Properties at 57112980 to arrange a viewing and seize this rare chance to own a piece of paradise in one of the most sought-after locations.`,
    ],
    address:"Near Bagatelle Mall",
    price: "Kolkata",
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    // thumbnail: beachfront.img1,
    images: [palmyre.img1,palmyre.img2]
  },
];